name: becmodel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - click
  - gdal
  - numpy
  - pandas
  - fiona
  - rasterio
  - geopandas
  - geojson
  - scikit-image
  - xlrd
  - cligj
  - mercantile
  - openpyxl
  - pip:
    - bcdata
    - terraincache