name: becmodel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip
  - click
  - gdal>=3.4
  - numpy
  - pandas
  - fiona
  - rasterio
  - geopandas>=0.10
  - geojson
  - scikit-image>=0.19
  - xlrd
  - cligj
  - mercantile
  - openpyxl
  - pip:
    - bcdata>=0.5.1
    - terraincache